# Generated by Django 4.0.6 on 2022-08-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yerba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=50)),
                ('peso', models.IntegerField()),
            ],
        ),
    ]
