# Generated by Django 4.0.6 on 2022-08-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatesApp', '0005_canal_canalmensaje_canalusuario_delete_mensaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contenido', models.CharField(max_length=400)),
                ('imagen', models.URLField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
